// AUTO-GENERATED by Phase 3 installer.
// Source of truth: content/worlds/*/*.json
// Re-run 02-create-dynamic-ui.sh after changing world JSON content.

import type { WorldId } from "../core/types";

export type JourneyWorldUIRecord = {
  id: WorldId;
  title: { en: string; ar: string };
  description: { en: string; ar: string };
  level: string;
  icon: string;
  badge: { en: string; ar: string };
  missionCount: number;
  vocabularyCount: number;
  characterCount: number;
  sceneCount: number;
  xpReward: number;
  order: number;
};

export const JOURNEY_WORLD_UI_REGISTRY = [
  {
    id: "airport",
    title: {
      en: "At the Airport",
      ar: "في المطار",
    },
    description: {
      en: "",
      ar: "",
    },
    level: "A2",
    icon: "✈️",
    badge: {
      en: "",
      ar: "",
    },
    missionCount: 3,
    vocabularyCount: 3,
    characterCount: 0,
    sceneCount: 3,
    xpReward: 340,
    order: 999,
  },
  {
    id: "canteen",
    title: {
      en: "At the Canteen",
      ar: "في المقصف",
    },
    description: {
      en: "",
      ar: "",
    },
    level: "A0",
    icon: "🥙",
    badge: {
      en: "",
      ar: "",
    },
    missionCount: 3,
    vocabularyCount: 3,
    characterCount: 1,
    sceneCount: 3,
    xpReward: 160,
    order: 999,
  },
  {
    id: "hospital",
    title: {
      en: "At the Hospital",
      ar: "في المستشفى",
    },
    description: {
      en: "",
      ar: "",
    },
    level: "A2",
    icon: "🏥",
    badge: {
      en: "",
      ar: "",
    },
    missionCount: 3,
    vocabularyCount: 3,
    characterCount: 0,
    sceneCount: 3,
    xpReward: 280,
    order: 999,
  },
  {
    id: "library",
    title: {
      en: "In the Library",
      ar: "في المكتبة",
    },
    description: {
      en: "",
      ar: "",
    },
    level: "A1",
    icon: "📚",
    badge: {
      en: "",
      ar: "",
    },
    missionCount: 3,
    vocabularyCount: 3,
    characterCount: 0,
    sceneCount: 3,
    xpReward: 190,
    order: 999,
  },
  {
    id: "market",
    title: {
      en: "At the Market",
      ar: "في السوق",
    },
    description: {
      en: "",
      ar: "",
    },
    level: "A1",
    icon: "🛍️",
    badge: {
      en: "",
      ar: "",
    },
    missionCount: 3,
    vocabularyCount: 3,
    characterCount: 0,
    sceneCount: 3,
    xpReward: 240,
    order: 999,
  },
  {
    id: "school",
    title: {
      en: "At School",
      ar: "في المدرسة",
    },
    description: {
      en: "",
      ar: "",
    },
    level: "A0",
    icon: "🏫",
    badge: {
      en: "",
      ar: "",
    },
    missionCount: 3,
    vocabularyCount: 3,
    characterCount: 2,
    sceneCount: 3,
    xpReward: 120,
    order: 999,
  },
  {
    id: "university",
    title: {
      en: "At University",
      ar: "في الجامعة",
    },
    description: {
      en: "",
      ar: "",
    },
    level: "B1",
    icon: "🎓",
    badge: {
      en: "",
      ar: "",
    },
    missionCount: 3,
    vocabularyCount: 3,
    characterCount: 0,
    sceneCount: 3,
    xpReward: 500,
    order: 999,
  },
] as JourneyWorldUIRecord[];
