import type { BayanStudioProject } from "./bayan-studio-schema";

export const BAYAN_STUDIO_STORAGE_KEY = "bayan-studio-project-v1";

export const DEFAULT_BAYAN_STUDIO_PROJECT: BayanStudioProject = {
  version: 1,
  updatedAt: new Date(0).toISOString(),
  characters: [
    {
      id: "sara-school",
      nameAr: "سارة",
      nameEn: "Sara",
      roleAr: "زميلة في المدرسة",
      worldId: "school",
      avatar: "س",
      voiceProvider: "studio",
      voiceId: "sara-school-primary",
      locale: "ar-QA",
      style: "ودود، واضح، مناسب للناشئة",
      speed: 0.92,
    },
    {
      id: "ahmed-canteen",
      nameAr: "أحمد",
      nameEn: "Ahmed",
      roleAr: "موظف المقهى",
      worldId: "canteen",
      avatar: "أ",
      voiceProvider: "studio",
      voiceId: "ahmed-canteen-primary",
      locale: "ar-QA",
      style: "دافئ، طبيعي، مهني",
      speed: 0.94,
    },
  ],
  voices: [
    {
      id: "school-listen-entry",
      worldId: "school",
      missionId: "listen",
      sceneId: "scene-listen",
      characterId: "sara-school",
      text: "مرحبًا، هل أنت طالب جديد؟",
      vocalizedText: "مَرْحَبًا، هَلْ أَنْتَ طالِبٌ جَديدٌ؟",
      audioPath: "/audio/bayan/dialogue/school/listen-entry.mp3",
      status: "missing",
    },
  ],
  ambience: [
    {
      id: "school-hallway",
      worldId: "school",
      labelAr: "ممر المدرسة",
      audioPath: "/audio/bayan/ambience/school-hallway.mp3",
      volume: 0.18,
      status: "missing",
    },
  ],
  worlds: [
    {
      id: "school",
      titleAr: "المدرسة",
      titleEn: "School",
      level: "A0",
      icon: "🏫",
      color: "#356cf6",
      locationAr: "بوابة المدرسة",
      ambienceAssetId: "school-hallway",
      characterIds: ["sara-school"],
      missions: [
        {
          id: "listen",
          titleAr: "يومك الأول في المدرسة",
          titleEn: "Your first day at school",
          xp: 20,
          scenes: [
            {
              id: "intro",
              kind: "intro",
              eyebrowAr: "المشهد",
              titleAr: "وصلت إلى بوابة المدرسة",
              bodyAr: "ابدأ التجربة دون قراءة النص، واستمع إلى الشخصية داخل السياق.",
              characterId: "sara-school",
            },
            {
              id: "listen",
              kind: "listen",
              eyebrowAr: "استمع أولًا",
              titleAr: "استمع قبل كشف النص",
              bodyAr: "حاول فهم المعنى من النبرة والموقف.",
              characterId: "sara-school",
              voiceAssetId: "school-listen-entry",
            },
            {
              id: "choice",
              kind: "choice",
              eyebrowAr: "تحقق من الفهم",
              titleAr: "ماذا سألت سارة؟",
              bodyAr: "اختر المعنى الصحيح.",
              choices: [
                {
                  id: "c1",
                  labelAr: "هل أنت طالب جديد؟",
                  correct: true,
                  feedbackAr: "صحيح.",
                },
                {
                  id: "c2",
                  labelAr: "هل تريد طعامًا؟",
                  correct: false,
                  feedbackAr: "هذا موقف مختلف.",
                },
              ],
            },
            {
              id: "speak",
              kind: "speak",
              eyebrowAr: "دورك",
              titleAr: "أجب بصوتك",
              bodyAr: "قدّم نفسك في جملة واضحة.",
              promptAr: "نعم، أنا طالب جديد.",
              hintAr: "استخدم: نعم، أنا...",
            },
            {
              id: "result",
              kind: "result",
              eyebrowAr: "النتيجة",
              titleAr: "أكملت المشهد",
              bodyAr: "تم حفظ التقدم.",
            },
          ],
        },
      ],
    },
  ],
  tutor: {
    enabled: true,
    correctionMode: "balanced",
    revealTranscriptAfterListen: true,
    minimumPronunciationScore: 72,
    maximumHints: 2,
    feedbackLanguage: "bilingual",
  },
};
