import type { ExperienceFoundationDocument } from "./types";

export const defaultExperienceFoundation: ExperienceFoundationDocument = {
  id: "family-experience-v3",
  name: "BAYAN Family Experience",
  slug: "parents",
  version: 3,
  status: "draft",
  theme: {
    primary: "#0d6b4d",
    secondary: "#ef8b27",
    background: "#f5f8f6",
    surface: "#ffffff",
    text: "#173b32",
    muted: "#6f857d",
    radius: 30,
    spacing: 22,
    fontScale: 1,
  },
  scenes: [
    {
      id: "scene-hero",
      type: "hero",
      name: "Hero of the Day",
      enabled: true,
      motion: "fade",
      audience: "all",
      data: {
        collection: "bayan_pulse_content",
        limit: 1,
        orderBy: "updatedAt",
        orderDirection: "desc",
        filters: [{ field: "kind", operator: "==", value: "hero" }],
      },
      bindings: {
        title: { mode: "field", value: "title" },
        subtitle: { mode: "field", value: "excerpt" },
        image: { mode: "field", value: "coverUrl" },
        buttonLabel: { mode: "static", value: "استكشف النبض" },
        buttonHref: { mode: "static", value: "#feed" },
      },
      style: { variant: "gradient", align: "start", minHeight: 420 },
    },
    {
      id: "scene-channels",
      type: "channels",
      name: "Dynamic Channels",
      enabled: true,
      motion: "slide-up",
      audience: "all",
      data: {
        collection: "bayan_channels",
        limit: 8,
        orderBy: "order",
        orderDirection: "asc",
      },
      bindings: {
        title: { mode: "static", value: "قنوات بيان" },
      },
      style: { variant: "minimal", align: "center", minHeight: 170 },
    },
    {
      id: "scene-stories",
      type: "stories",
      name: "Stories",
      enabled: true,
      motion: "slide-up",
      audience: "all",
      data: {
        collection: "bayan_pulse_stories",
        limit: 8,
        orderBy: "publishedAt",
        orderDirection: "desc",
      },
      bindings: {
        title: { mode: "static", value: "قصص اليوم" },
      },
      style: { variant: "minimal", align: "start", minHeight: 180 },
    },
    {
      id: "scene-feed",
      type: "feed",
      name: "School Pulse",
      enabled: true,
      motion: "fade",
      audience: "all",
      data: {
        collection: "bayan_social_posts",
        limit: 20,
        orderBy: "publishedAt",
        orderDirection: "desc",
        filters: [{ field: "status", operator: "==", value: "published" }],
      },
      bindings: {
        title: { mode: "static", value: "نبض بيان" },
      },
      style: { variant: "editorial", align: "start", minHeight: 500 },
    },
    {
      id: "scene-events",
      type: "events",
      name: "Upcoming Events",
      enabled: true,
      motion: "slide-up",
      audience: "all",
      data: {
        collection: "bayan_events",
        limit: 4,
        orderBy: "startAt",
        orderDirection: "asc",
      },
      bindings: {
        title: { mode: "static", value: "الفعاليات القادمة" },
      },
      style: { variant: "glass", align: "start", minHeight: 240 },
    },
    {
      id: "scene-achievements",
      type: "achievements",
      name: "Hall of Fame",
      enabled: true,
      motion: "scale",
      audience: "all",
      data: {
        collection: "bayan_achievements",
        limit: 6,
        orderBy: "publishedAt",
        orderDirection: "desc",
      },
      bindings: {
        title: { mode: "static", value: "لوحة الشرف" },
      },
      style: { variant: "editorial", align: "start", minHeight: 280 },
    },
  ],
};
